version: '3.9'
services:
  python:
    image: python
    build: 
      context: .
      dockerfile: python.Dockerfile
    volumes:
      - ./:/root/projects
    environment:
      # `pipenv` will create an environment in the working directory
      - PIPENV_VENV_IN_PROJECT=1
    deploy:
      resources:
        limits:
          # number of cores this container can use (can be 0.5 means half core)
          cpus: '14'
          # maximun RAM this container can use
          memory: '50G'
        # reservations:
        #   devices:
        #     - driver: nvidia
        #       count: 1
        #       capabilities: [gpu]
  latex:
    image: latex
    build: 
      context: .
      dockerfile: latex.Dockerfile
    volumes:
      - ./:/root/projects